In [244]:
import numpy as np

In [245]:
array_from_list = np.array([1, 2, 3])
array_from_list

array([1, 2, 3])

In [246]:
list_a = [1, 2, 3]
type(list_a)    

list

In [247]:
array_from_list = np.array(list_a)
array_from_list

array([1, 2, 3])

In [248]:
type(array_from_list)

numpy.ndarray

In [249]:
tuple_a = (1, 2, 3)
tuple_a

(1, 2, 3)

In [250]:
type(tuple_a)

tuple

In [251]:
array_from_tuple = np.array(tuple_a)
print(array_from_tuple)
print(type(array_from_tuple))

[1 2 3]
<class 'numpy.ndarray'>


In [252]:
array_from_list + 5

array([6, 7, 8])

In [253]:
array_from_tuple + 5

array([6, 7, 8])

In [254]:
set_a = {1, 2, 3, 4, 4}
print(set_a)
print(type(set_a))

{1, 2, 3, 4}
<class 'set'>


In [255]:
array_from_set = np.array(set_a)
array_from_set

array({1, 2, 3, 4}, dtype=object)

In [256]:
try:
    array_from_set + 5
except Exception as e:
    print(e)

unsupported operand type(s) for +: 'set' and 'int'


In [257]:
dict_a = {1: 'a', 2: 'b'}
print(dict_a)
print(type(dict_a))

{1: 'a', 2: 'b'}
<class 'dict'>


In [258]:
array_from_dict = np.array(dict_a)
array_from_dict

array({1: 'a', 2: 'b'}, dtype=object)

In [259]:
try:
    array_from_dict + 5
except Exception as e:
    print(e)

unsupported operand type(s) for +: 'dict' and 'int'


In [260]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9], 
                     [10, 11, 12]])
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [261]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [262]:
array_2d[1][1], array_2d[3][2]

(5, 12)

In [263]:
try:
    np.array([[1, 2, 3],
          [4, 5],
          [7, 8, 9],
          [10]])
except Exception as e:
    print(e)

setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.


In [264]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
                     [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [265]:
array_3d[0][2][1]

8

In [266]:
array_3d[1][3][2]

24

In [267]:
array_from_list

array([1, 2, 3])

In [268]:
array_from_list.size

3

In [269]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [270]:
array_2d.size

12

In [271]:
array_3d.size

24

In [272]:
array_2d.ndim

2

In [273]:
array_3d.ndim

3

In [274]:
array_from_list.shape

(3,)

In [275]:
array_2d.shape

(4, 3)

In [276]:
array_3d.shape

(2, 4, 3)

In [277]:
len(array_3d.shape), array_3d.ndim

(3, 3)

In [278]:
2 * 4 * 3, array_3d.size

(24, 24)

In [279]:
array_from_list.itemsize

8

In [280]:
array_2d.itemsize

8

In [281]:
array_3d.itemsize

8

In [282]:
array_from_list.nbytes, 3 * 8

(24, 24)

In [283]:
array_2d.nbytes, 24 * 8, array_3d.size * array_3d.itemsize

(96, 192, 192)

In [284]:
array_from_list.dtype

dtype('int64')

In [285]:
array_2d.dtype

dtype('int64')

In [286]:
array_3d.dtype

dtype('int64')

In [287]:
array_32bits = np.array([1, 2, 3], dtype=np.int32)
array_32bits

array([1, 2, 3], dtype=int32)

In [288]:
array_32bits.itemsize

4

In [289]:
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

In [290]:
np.array([1, 2, 3], dtype=np.str_)

array(['1', '2', '3'], dtype='<U1')

In [291]:
np.array([1, 2, 3], dtype=float).dtype

dtype('float64')