In [2]:
import numpy as np

In [3]:
def filter_and_replace(arr, condition, new_value):
    """
    Subistitui os valores em 'arr' que atendem à 'condition' por 'nem_value'.
    - arr: Matriz de dados
    - condition: Função que define a condição (ex: arr < 0)
    - new_value: Valor a ser atribuído onde a condição é verdadeira
    """

    # Indexação condicional e atribuição
    arr[condition(arr)] = new_value
    return arr

In [4]:
# Exemplo de uso
arr = np.random.randn(5, 5) # Criando uma matriz aleatória com valores negativos e positivos
print("Antes da substituição: ")
print(arr)

Antes da substituição: 
[[ 0.61364933  0.52188651 -0.88082784  0.76805664 -0.23841503]
 [-0.08958814  0.37946212  0.38428378 -0.34281043 -0.92674939]
 [-1.60313434  1.69226804  0.41184588 -0.85819246 -0.03485739]
 [ 0.39367051 -0.96668316  0.65978313 -1.03412518  0.36534396]
 [-0.42071915 -1.48928886 -1.19010714 -0.28834845 -0.12264784]]


In [5]:
# Substituindo valores menores que 0 por 0
arr = filter_and_replace(arr, lambda x: x < 0, 0)
print('\nDepois da substituição: ')
print(arr)


Depois da substituição: 
[[0.61364933 0.52188651 0.         0.76805664 0.        ]
 [0.         0.37946212 0.38428378 0.         0.        ]
 [0.         1.69226804 0.41184588 0.         0.        ]
 [0.39367051 0.         0.65978313 0.         0.36534396]
 [0.         0.         0.         0.         0.        ]]
