In [1]:
import numpy as np

In [2]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [3]:
array_3d.tolist()

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [4]:
type(array_3d.tolist())

list

In [5]:
array_3d[0, 1, 2]

7

In [6]:
array_3d.item((1,0,2))

15

In [7]:
array_3d[1,0,2]

15

In [8]:
array_3d.item(14)

15

In [9]:
array_3d.itemset(14,50)
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 50, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [10]:
array_3d.item(14)

50

In [11]:
array_3d.itemset((1,0,2), 100)
array_3d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14, 100,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [12]:
array_3d.item((1,0,2))

100

In [13]:
array_3d[1,0,2] = 150
array_3d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14, 150,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [14]:
array_3d = np.arange(1, 25).reshape(2, 4, 3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [15]:
array_view = array_3d.view()
array_view

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [16]:
array_view[0,0,0] = 0
array_view

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [17]:
array_3d

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [18]:
array_3d = np.arange(1,25).reshape(2,4,3)
array_copy = array_3d.copy()
array_copy

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [19]:
array_copy[0,0,0] = 99
array_copy

array([[[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [21]:
array_3d = np.arange(1,25).reshape(2,4,3)
array_3d.fill(55)
array_3d

array([[[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]]])