In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng(seed=1)

In [3]:
rng.random()

0.5118216247002567

In [4]:
rng = np.random.default_rng(seed=2)
rng.random()

0.2616121342493164

In [5]:
rng.random(size=10)

array([0.29849114, 0.81422574, 0.09191594, 0.60010053, 0.72856053,
       0.18790107, 0.05514663, 0.27496937, 0.65743301, 0.56226566])

In [6]:
rng.random(size=(5,2))

array([[0.15006226, 0.43263079],
       [0.6692973 , 0.42278467],
       [0.6331844 , 0.96743595],
       [0.68306482, 0.39162483],
       [0.18725257, 0.34596067]])

In [7]:
rng.integers(4, size = 5)

array([2, 2, 2, 3, 3])

In [8]:
rng.integers(low = 10, high = [15,54,100])

array([13, 52, 38])

In [9]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
rng.choice(a = array, size = 5)

array([9, 9, 2, 4, 5])

In [11]:
rng.choice(a = array, size = 10)

array([6, 7, 1, 4, 1, 9, 2, 4, 8, 5])

In [12]:
rng.choice(a = array, size = 10, replace = False)

array([9, 0, 4, 8, 2, 1, 6, 3, 5, 7])

In [13]:
array = np.array([1, 2, 3])
p = np.array([0.5, 0.4, 0.1]) # a soma deve ser igual a 1 (100%)

In [14]:
rng.choice(a = array, p = p, size = 10)

array([2, 1, 2, 1, 2, 1, 1, 1, 2, 1])

In [15]:
array_2d = np.arange(0,20).reshape(4,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
rng.choice(a = array_2d, size = 2, axis = 0)

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [17]:
rng.choice(a = array_2d, size = 2, axis = 1)

array([[ 4,  1],
       [ 9,  6],
       [14, 11],
       [19, 16]])

In [18]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
rng.shuffle(array)
array

array([2, 1, 9, 5, 3, 4, 7, 8, 0, 6])

In [20]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
rng.shuffle(array, axis = 0)
array

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

In [22]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
rng.shuffle(array, axis = 1)
array

array([[ 2,  3,  0,  4,  1],
       [ 7,  8,  5,  9,  6],
       [12, 13, 10, 14, 11],
       [17, 18, 15, 19, 16]])

In [24]:
# array = np.arange(10)
# np.shuffle(array)

rng.permutation(10)

array([9, 7, 8, 5, 0, 4, 3, 6, 1, 2])

In [25]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
rng.permutation(array, axis = 0)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [27]:
rng.permutation(array, axis = 1)

array([[ 4,  2,  1,  0,  3],
       [ 9,  7,  6,  5,  8],
       [14, 12, 11, 10, 13],
       [19, 17, 16, 15, 18]])

In [28]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
rng.permuted(array, axis = 0)

array([[10,  1,  7, 18, 19],
       [ 0, 16,  2,  3, 14],
       [15,  6, 17,  8,  9],
       [ 5, 11, 12, 13,  4]])

In [30]:
rng.permuted(array, axis = 1)

array([[ 3,  2,  0,  4,  1],
       [ 5,  7,  8,  9,  6],
       [10, 13, 14, 11, 12],
       [16, 19, 17, 18, 15]])