In [411]:
import numpy as np

In [412]:
rng = np.random.default_rng(seed=1)

In [413]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3,5,4).round(3)

In [414]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [415]:
array[0]


array([[51.037, 52.465, 50.991, 46.091],
       [52.716, 51.339, 48.389, 51.743],
       [51.094, 50.882, 50.085, 51.64 ],
       [47.791, 49.511, 48.554, 51.797],
       [50.119, 49.123, 47.654, 49.228]])

In [416]:
array[1]

array([[50.024, 49.173, 53.882, 53.02 ],
       [41.867, 44.333, 49.476, 48.733],
       [50.641, 50.652, 56.354, 46.664],
       [48.867, 56.128, 51.94 , 51.989],
       [48.458, 45.056, 50.502, 50.327]])

In [417]:
array[2]

array([[46.318, 47.95 , 49.784, 47.166],
       [49.705, 50.286, 50.107, 48.481],
       [51.781, 52.674, 50.963, 47.545],
       [52.195, 48.496, 52.637, 46.785],
       [52.743, 49.94 , 46.254, 49.058]])

In [418]:
array.shape

(3, 5, 4)

In [419]:
array.item(2,1,0)

49.705

In [420]:
array.itemset((2,1,0), 49.709)

In [421]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.709, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [422]:
array.item(2,1,0)

49.709

In [423]:
array_view = array.view()
array_view

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.709, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [424]:
array.itemset((2,1,0), 49.705)
array.item(2,1,0)

49.705

In [425]:
array_view.item(2,1,0)

49.705

In [426]:
array_1 = rng.normal(loc=50, scale=3, size=60).reshape(3,5,4).round(3)
array_copy = array.copy()
array_copy

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [427]:
array.shape

(3, 5, 4)

In [428]:
array.item(2,1,0)

49.705

In [429]:
array.itemset((2,1,0), 49.709)
array.item(2,1,0)

49.709

In [430]:
array_view = array.view()
array_view

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.709, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [431]:
array_view[2,1,0] = 49.705

In [432]:
array[2,1,0]

49.705

In [433]:
array_view[2,1,0]

49.705

In [434]:
array_copy = array.copy()

In [435]:
array_copy[2,1,0] = 49.705

In [436]:
array[2,1,0]

49.705

In [437]:
array.item((2,1,0))

49.705

In [438]:
array_copy.item((2,1,0))

49.705

In [439]:
array.reshape(3,20)

array([[51.037, 52.465, 50.991, 46.091, 52.716, 51.339, 48.389, 51.743,
        51.094, 50.882, 50.085, 51.64 , 47.791, 49.511, 48.554, 51.797,
        50.119, 49.123, 47.654, 49.228],
       [50.024, 49.173, 53.882, 53.02 , 41.867, 44.333, 49.476, 48.733,
        50.641, 50.652, 56.354, 46.664, 48.867, 56.128, 51.94 , 51.989,
        48.458, 45.056, 50.502, 50.327],
       [46.318, 47.95 , 49.784, 47.166, 49.705, 50.286, 50.107, 48.481,
        51.781, 52.674, 50.963, 47.545, 52.195, 48.496, 52.637, 46.785,
        52.743, 49.94 , 46.254, 49.058]])

In [440]:
array_transpose = array.transpose((1,2,0))

In [441]:
array_transpose

array([[[51.037, 50.024, 46.318],
        [52.465, 49.173, 47.95 ],
        [50.991, 53.882, 49.784],
        [46.091, 53.02 , 47.166]],

       [[52.716, 41.867, 49.705],
        [51.339, 44.333, 50.286],
        [48.389, 49.476, 50.107],
        [51.743, 48.733, 48.481]],

       [[51.094, 50.641, 51.781],
        [50.882, 50.652, 52.674],
        [50.085, 56.354, 50.963],
        [51.64 , 46.664, 47.545]],

       [[47.791, 48.867, 52.195],
        [49.511, 56.128, 48.496],
        [48.554, 51.94 , 52.637],
        [51.797, 51.989, 46.785]],

       [[50.119, 48.458, 52.743],
        [49.123, 45.056, 49.94 ],
        [47.654, 50.502, 46.254],
        [49.228, 50.327, 49.058]]])

In [442]:
array_transpose.shape

(5, 4, 3)

In [443]:
array_swapaxes = array.swapaxes(2,1)

In [444]:
array_swapaxes

array([[[51.037, 52.716, 51.094, 47.791, 50.119],
        [52.465, 51.339, 50.882, 49.511, 49.123],
        [50.991, 48.389, 50.085, 48.554, 47.654],
        [46.091, 51.743, 51.64 , 51.797, 49.228]],

       [[50.024, 41.867, 50.641, 48.867, 48.458],
        [49.173, 44.333, 50.652, 56.128, 45.056],
        [53.882, 49.476, 56.354, 51.94 , 50.502],
        [53.02 , 48.733, 46.664, 51.989, 50.327]],

       [[46.318, 49.705, 51.781, 52.195, 52.743],
        [47.95 , 50.286, 52.674, 48.496, 49.94 ],
        [49.784, 50.107, 50.963, 52.637, 46.254],
        [47.166, 48.481, 47.545, 46.785, 49.058]]])

In [445]:
array_swapaxes.shape

(3, 4, 5)

In [446]:
array.flatten()

array([51.037, 52.465, 50.991, 46.091, 52.716, 51.339, 48.389, 51.743,
       51.094, 50.882, 50.085, 51.64 , 47.791, 49.511, 48.554, 51.797,
       50.119, 49.123, 47.654, 49.228, 50.024, 49.173, 53.882, 53.02 ,
       41.867, 44.333, 49.476, 48.733, 50.641, 50.652, 56.354, 46.664,
       48.867, 56.128, 51.94 , 51.989, 48.458, 45.056, 50.502, 50.327,
       46.318, 47.95 , 49.784, 47.166, 49.705, 50.286, 50.107, 48.481,
       51.781, 52.674, 50.963, 47.545, 52.195, 48.496, 52.637, 46.785,
       52.743, 49.94 , 46.254, 49.058])

In [447]:
array.ravel()

array([51.037, 52.465, 50.991, 46.091, 52.716, 51.339, 48.389, 51.743,
       51.094, 50.882, 50.085, 51.64 , 47.791, 49.511, 48.554, 51.797,
       50.119, 49.123, 47.654, 49.228, 50.024, 49.173, 53.882, 53.02 ,
       41.867, 44.333, 49.476, 48.733, 50.641, 50.652, 56.354, 46.664,
       48.867, 56.128, 51.94 , 51.989, 48.458, 45.056, 50.502, 50.327,
       46.318, 47.95 , 49.784, 47.166, 49.705, 50.286, 50.107, 48.481,
       51.781, 52.674, 50.963, 47.545, 52.195, 48.496, 52.637, 46.785,
       52.743, 49.94 , 46.254, 49.058])

In [448]:
array_first_day = array[0:1]

In [449]:
array_first_day

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]]])

In [450]:
array_first_day.ndim, array_first_day.shape

(3, (1, 5, 4))

In [451]:
array_squeeze = array_first_day.squeeze()

In [452]:
array_squeeze

array([[51.037, 52.465, 50.991, 46.091],
       [52.716, 51.339, 48.389, 51.743],
       [51.094, 50.882, 50.085, 51.64 ],
       [47.791, 49.511, 48.554, 51.797],
       [50.119, 49.123, 47.654, 49.228]])

In [453]:
array_squeeze.shape

(5, 4)

In [454]:
array.take(indices=[12,25,31,40])

array([47.791, 44.333, 46.664, 46.318])

In [455]:
array.take(indices=[[12,31],[25,40]])

array([[47.791, 46.664],
       [44.333, 46.318]])

In [456]:
array.put(indices=[12,25,31,40], values=np.nan)

In [457]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [   nan, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867,    nan, 49.476, 48.733],
        [50.641, 50.652, 56.354,    nan],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[   nan, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [458]:
array_repeat_axis_0 = array.repeat(repeats=2, axis=0)

In [459]:
array_repeat_axis_0

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [   nan, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [   nan, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867,    nan, 49.476, 48.733],
        [50.641, 50.652, 56.354,    nan],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867,    nan, 49.476, 48.733],
        [50.641, 50.652, 56.354,    nan],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[   nan, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 5

In [460]:
array_repeat_axis_0.shape

(6, 5, 4)

In [461]:
array_repeat_axis_1 = array.repeat(repeats=2, axis=1)

In [462]:
array_repeat_axis_1

array([[[51.037, 52.465, 50.991, 46.091],
        [51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [51.094, 50.882, 50.085, 51.64 ],
        [   nan, 49.511, 48.554, 51.797],
        [   nan, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [50.024, 49.173, 53.882, 53.02 ],
        [41.867,    nan, 49.476, 48.733],
        [41.867,    nan, 49.476, 48.733],
        [50.641, 50.652, 56.354,    nan],
        [50.641, 50.652, 56.354,    nan],
        [48.867, 56.128, 51.94 , 51.989],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327],
        [48.458, 45.056, 50.502, 50.327]],

       [[   nan, 47.95 , 49.784, 47.166],
        [   nan, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [49.705, 50.286, 50.10

In [463]:
array_repeat_axis_2 = array.repeat(repeats=2, axis=2)

In [464]:
array_repeat_axis_2

array([[[51.037, 51.037, 52.465, 52.465, 50.991, 50.991, 46.091, 46.091],
        [52.716, 52.716, 51.339, 51.339, 48.389, 48.389, 51.743, 51.743],
        [51.094, 51.094, 50.882, 50.882, 50.085, 50.085, 51.64 , 51.64 ],
        [   nan,    nan, 49.511, 49.511, 48.554, 48.554, 51.797, 51.797],
        [50.119, 50.119, 49.123, 49.123, 47.654, 47.654, 49.228, 49.228]],

       [[50.024, 50.024, 49.173, 49.173, 53.882, 53.882, 53.02 , 53.02 ],
        [41.867, 41.867,    nan,    nan, 49.476, 49.476, 48.733, 48.733],
        [50.641, 50.641, 50.652, 50.652, 56.354, 56.354,    nan,    nan],
        [48.867, 48.867, 56.128, 56.128, 51.94 , 51.94 , 51.989, 51.989],
        [48.458, 48.458, 45.056, 45.056, 50.502, 50.502, 50.327, 50.327]],

       [[   nan,    nan, 47.95 , 47.95 , 49.784, 49.784, 47.166, 47.166],
        [49.705, 49.705, 50.286, 50.286, 50.107, 50.107, 48.481, 48.481],
        [51.781, 51.781, 52.674, 52.674, 50.963, 50.963, 47.545, 47.545],
        [52.195, 52.195, 48.496, 4

In [465]:
array_repeat_axis_2.shape

(3, 5, 8)

In [466]:
array_copy = array.copy()

In [467]:
array_copy.sort(axis=0)

In [468]:
array_copy

array([[[50.024, 47.95 , 49.784, 46.091],
        [41.867, 50.286, 48.389, 48.481],
        [50.641, 50.652, 50.085, 47.545],
        [48.867, 48.496, 48.554, 46.785],
        [48.458, 45.056, 46.254, 49.058]],

       [[51.037, 49.173, 50.991, 47.166],
        [49.705, 51.339, 49.476, 48.733],
        [51.094, 50.882, 50.963, 51.64 ],
        [52.195, 49.511, 51.94 , 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[   nan, 52.465, 53.882, 53.02 ],
        [52.716,    nan, 50.107, 51.743],
        [51.781, 52.674, 56.354,    nan],
        [   nan, 56.128, 52.637, 51.989],
        [52.743, 49.94 , 50.502, 50.327]]])

In [469]:
array_copy = array.copy()

In [470]:
array_copy.sort(axis=1)

In [471]:
array_copy

array([[[50.119, 49.123, 47.654, 46.091],
        [51.037, 49.511, 48.389, 49.228],
        [51.094, 50.882, 48.554, 51.64 ],
        [52.716, 51.339, 50.085, 51.743],
        [   nan, 52.465, 50.991, 51.797]],

       [[41.867, 45.056, 49.476, 48.733],
        [48.458, 49.173, 50.502, 50.327],
        [48.867, 50.652, 51.94 , 51.989],
        [50.024, 56.128, 53.882, 53.02 ],
        [50.641,    nan, 56.354,    nan]],

       [[49.705, 47.95 , 46.254, 46.785],
        [51.781, 48.496, 49.784, 47.166],
        [52.195, 49.94 , 50.107, 47.545],
        [52.743, 50.286, 50.963, 48.481],
        [   nan, 52.674, 52.637, 49.058]]])

In [472]:
array_copy = array.copy()

In [473]:
array_copy.sort(axis=2)

In [474]:
array_copy

array([[[46.091, 50.991, 51.037, 52.465],
        [48.389, 51.339, 51.743, 52.716],
        [50.085, 50.882, 51.094, 51.64 ],
        [48.554, 49.511, 51.797,    nan],
        [47.654, 49.123, 49.228, 50.119]],

       [[49.173, 50.024, 53.02 , 53.882],
        [41.867, 48.733, 49.476,    nan],
        [50.641, 50.652, 56.354,    nan],
        [48.867, 51.94 , 51.989, 56.128],
        [45.056, 48.458, 50.327, 50.502]],

       [[47.166, 47.95 , 49.784,    nan],
        [48.481, 49.705, 50.107, 50.286],
        [47.545, 50.963, 51.781, 52.674],
        [46.785, 48.496, 52.195, 52.637],
        [46.254, 49.058, 49.94 , 52.743]]])

In [475]:
indices_axis_0 = array.argsort(axis=0)

In [476]:
indices_axis_0

array([[[1, 2, 2, 0],
        [1, 2, 0, 2],
        [1, 1, 0, 2],
        [1, 2, 0, 2],
        [1, 1, 2, 2]],

       [[0, 1, 0, 2],
        [2, 0, 1, 1],
        [0, 0, 2, 0],
        [2, 0, 1, 0],
        [0, 0, 0, 0]],

       [[2, 0, 1, 1],
        [0, 1, 2, 0],
        [2, 2, 1, 1],
        [0, 1, 2, 1],
        [2, 2, 1, 1]]])

In [477]:
indices_axis_1 = array.argsort(axis=1)

In [478]:
indices_axis_1

array([[[4, 4, 4, 0],
        [0, 3, 1, 4],
        [2, 2, 3, 2],
        [1, 1, 2, 1],
        [3, 0, 0, 3]],

       [[1, 4, 1, 1],
        [4, 0, 4, 4],
        [3, 2, 3, 3],
        [0, 3, 0, 0],
        [2, 1, 2, 2]],

       [[1, 0, 4, 3],
        [2, 3, 0, 0],
        [3, 4, 1, 2],
        [4, 1, 2, 1],
        [0, 2, 3, 4]]])

In [479]:
indices_axis_2 = array.argsort(axis=2)

In [480]:
indices_axis_2

array([[[3, 2, 0, 1],
        [2, 1, 3, 0],
        [2, 1, 0, 3],
        [2, 1, 3, 0],
        [2, 1, 3, 0]],

       [[1, 0, 3, 2],
        [0, 3, 2, 1],
        [0, 1, 2, 3],
        [0, 2, 3, 1],
        [1, 0, 3, 2]],

       [[3, 1, 2, 0],
        [3, 0, 2, 1],
        [3, 2, 0, 1],
        [3, 1, 0, 2],
        [2, 3, 1, 0]]])

In [481]:
array_flatten = array.flatten()

In [482]:
array_flatten

array([51.037, 52.465, 50.991, 46.091, 52.716, 51.339, 48.389, 51.743,
       51.094, 50.882, 50.085, 51.64 ,    nan, 49.511, 48.554, 51.797,
       50.119, 49.123, 47.654, 49.228, 50.024, 49.173, 53.882, 53.02 ,
       41.867,    nan, 49.476, 48.733, 50.641, 50.652, 56.354,    nan,
       48.867, 56.128, 51.94 , 51.989, 48.458, 45.056, 50.502, 50.327,
          nan, 47.95 , 49.784, 47.166, 49.705, 50.286, 50.107, 48.481,
       51.781, 52.674, 50.963, 47.545, 52.195, 48.496, 52.637, 46.785,
       52.743, 49.94 , 46.254, 49.058])

In [483]:
array_flatten.sort()

In [484]:
array_flatten

array([41.867, 45.056, 46.091, 46.254, 46.785, 47.166, 47.545, 47.654,
       47.95 , 48.389, 48.458, 48.481, 48.496, 48.554, 48.733, 48.867,
       49.058, 49.123, 49.173, 49.228, 49.476, 49.511, 49.705, 49.784,
       49.94 , 50.024, 50.085, 50.107, 50.119, 50.286, 50.327, 50.502,
       50.641, 50.652, 50.882, 50.963, 50.991, 51.037, 51.094, 51.339,
       51.64 , 51.743, 51.781, 51.797, 51.94 , 51.989, 52.195, 52.465,
       52.637, 52.674, 52.716, 52.743, 53.02 , 53.882, 56.128, 56.354,
          nan,    nan,    nan,    nan])

In [485]:
array_filtered = array_flatten[:15]

In [486]:
array_filtered

array([41.867, 45.056, 46.091, 46.254, 46.785, 47.166, 47.545, 47.654,
       47.95 , 48.389, 48.458, 48.481, 48.496, 48.554, 48.733])

In [487]:
indices = array_filtered.searchsorted([40.50, 42.357, 47.025, 48.952])

In [488]:
indices

array([ 0,  1,  5, 15])

In [489]:
array_2D = array[0]

In [490]:
array_2D

array([[51.037, 52.465, 50.991, 46.091],
       [52.716, 51.339, 48.389, 51.743],
       [51.094, 50.882, 50.085, 51.64 ],
       [   nan, 49.511, 48.554, 51.797],
       [50.119, 49.123, 47.654, 49.228]])

In [491]:
array_2D.shape

(5, 4)

In [492]:
array_2D.diagonal()

array([51.037, 51.339, 50.085, 51.797])