In [169]:
import numpy as np

In [170]:
array_a = np.array([0, 1, 2, 3])

In [171]:
array_b = np.append(array_a, 4)

In [172]:
array_b

array([0, 1, 2, 3, 4])

In [173]:
id(array_a) == id(array_b)

False

In [174]:
id(array_a), id(array_b)

(124476341200112, 124476341202032)

In [175]:
def id_comprasion(array_a, array_b):
    return np.array_equal(array_a, array_b)

In [176]:
np.array_equal(array_a, array_b)

False

In [177]:
array_c = np.array([3, False, 7.9, 0.0])

In [178]:
array_c

array([3. , 0. , 7.9, 0. ])

In [179]:
for i in array_c:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [180]:
array_c.dtype

dtype('float64')

In [181]:
array_d = np.array([10, 11, 12, 13])
array_e = np.array([1, 2, 3, 4])

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

In [182]:
adicao_array = array_d + array_e
adicao_array

array([11, 13, 15, 17])

In [183]:
subtracao_array = array_d - array_e
subtracao_array

array([9, 9, 9, 9])

In [184]:
multiplicacao_array = array_d * array_e
multiplicacao_array

array([10, 22, 36, 52])

In [185]:
divisao_array = array_d / array_e
divisao_array

array([10.  ,  5.5 ,  4.  ,  3.25])

In [186]:
adicao_array_2 = array_d + 2
adicao_array_2

array([12, 13, 14, 15])

In [187]:
subtracao_array_2 = array_d - 2
subtracao_array_2

array([ 8,  9, 10, 11])

In [188]:
multiplicacao_array_2 = array_d * 2
multiplicacao_array_2

array([20, 22, 24, 26])

In [189]:
divisao_array_2 = array_d / 2
divisao_array_2

array([5. , 5.5, 6. , 6.5])