In [99]:
import numpy as np

In [100]:
# Criando um array exemplo para demonstrar os métodos
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f'Array original: {arr}')

Array original: [[1 2 3]
 [4 5 6]]


In [101]:
# 1 - Método tolist()
# Converte um Array Numpy em uma lista Python
lista = arr.tolist()
print(f'1. Demonstração do tolist(): {lista}')
print(f'Array convertido para lista: {arr}')
print(f'Tipo do resultado: {type(lista)}')

1. Demonstração do tolist(): [[1, 2, 3], [4, 5, 6]]
Array convertido para lista: [[1 2 3]
 [4 5 6]]
Tipo do resultado: <class 'list'>


In [102]:
# 2 - Método item()
# Retorna um único elemento como um objeto Python escalar
primeiro_elemento = arr.item(0)
print(f'2. Demonstração do item(): {primeiro_elemento}')
print(f'Tipo do resultado: {type(primeiro_elemento)}')

2. Demonstração do item(): 1
Tipo do resultado: <class 'int'>


In [103]:
# 3 - Método itemset()
# Define o valor de um elemento específico
arr_itemset = arr.copy() # Obtém o primeiro elemento
arr_itemset.itemset(0, 99)
print('3. Demonstração do itemset():')
print(f'Array após itemset(0, 99): {arr_itemset}')
print(arr_itemset)

3. Demonstração do itemset():
Array após itemset(0, 99): [[99  2  3]
 [ 4  5  6]]
[[99  2  3]
 [ 4  5  6]]


In [104]:
# 4 - Método view()
# Cria uma nova visualização do mesmo dados em memória
view_arr = arr.view()
print(f'4. Demonstração do view(): {view_arr}')
print(f'Modificando o view arr: {view_arr}')
view_arr[0,0] = 100 # Modifica a view
print(f'Array original também modificado: {arr}') # O array original também é modificado

4. Demonstração do view(): [[1 2 3]
 [4 5 6]]
Modificando o view arr: [[1 2 3]
 [4 5 6]]
Array original também modificado: [[100   2   3]
 [  4   5   6]]


In [105]:
# 5 - Método copy()
# Cria uma cópia indenpendente do array
copia_arr = arr.copy()
print(f'5. Demonstração do copy(): {copia_arr}')
print('Modificando o cópia')
copia_arr[0,0] = 200 # Modifica a cópia
print(f'Array original també modificado: {arr}') # O array original també é modificado

5. Demonstração do copy(): [[100   2   3]
 [  4   5   6]]
Modificando o cópia
Array original també modificado: [[100   2   3]
 [  4   5   6]]


In [106]:
# 6 - Método fill()
# Preenche oa array com um valor específico
arr_fill = arr.copy()
arr_fill.fill(7)
print(f'6. Demonstração do fill()')
print(f'Array preenchido com 7: {arr_fill}')

6. Demonstração do fill()
Array preenchido com 7: [[7 7 7]
 [7 7 7]]
