In [4]:
import numpy as np

In [5]:
shape = (4, 3)

In [6]:
np.zeros(shape=shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(shape=shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full(shape=shape, fill_value=7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
np.full(shape=shape, fill_value=8.9)

array([[8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9],
       [8.9, 8.9, 8.9]])

In [13]:
np.full(shape=shape, fill_value=False)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
np.identity(shape[0])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(N = 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.arange(start=4, stop=21, step=2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
np.arange(49, 25, -2)

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27])

In [44]:
np.linspace(start=49, stop=27, num=12).astype(int)

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27])

In [48]:
np.arange(start=0, stop=1.01, step=0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [83]:
np.linspace(start=0, stop=38, num=5)

array([ 0. ,  9.5, 19. , 28.5, 38. ])

In [98]:
np.logspace(start=0, stop=5, num=6).astype(int)

array([     1,     10,    100,   1000,  10000, 100000])

In [103]:
np.geomspace(start=35, stop=48000, num=5).astype(int)

array([   35,   212,  1296,  7887, 48000])