In [31]:
import numpy as np

In [32]:
rng = np.random.default_rng(seed=1)

In [33]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3,5,4).round(3)

In [34]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [35]:
array[0]

array([[51.037, 52.465, 50.991, 46.091],
       [52.716, 51.339, 48.389, 51.743],
       [51.094, 50.882, 50.085, 51.64 ],
       [47.791, 49.511, 48.554, 51.797],
       [50.119, 49.123, 47.654, 49.228]])

In [36]:
array[1]

array([[50.024, 49.173, 53.882, 53.02 ],
       [41.867, 44.333, 49.476, 48.733],
       [50.641, 50.652, 56.354, 46.664],
       [48.867, 56.128, 51.94 , 51.989],
       [48.458, 45.056, 50.502, 50.327]])

In [37]:
array[2]

array([[46.318, 47.95 , 49.784, 47.166],
       [49.705, 50.286, 50.107, 48.481],
       [51.781, 52.674, 50.963, 47.545],
       [52.195, 48.496, 52.637, 46.785],
       [52.743, 49.94 , 46.254, 49.058]])

In [38]:
array.shape

(3, 5, 4)

In [39]:
array[0][0]

array([51.037, 52.465, 50.991, 46.091])

In [40]:
array[0, ::5]

array([[51.037, 52.465, 50.991, 46.091]])

In [41]:
array[1][1]

array([41.867, 44.333, 49.476, 48.733])

In [42]:
array[1, 1::4]

array([[41.867, 44.333, 49.476, 48.733]])

In [43]:
array[1, 2::3]

array([[50.641, 50.652, 56.354, 46.664]])

In [44]:
array[0, [0, 1, 2, 3, 4], [3]]

array([46.091, 51.743, 51.64 , 51.797, 49.228])

In [45]:
array[0, [4]]

array([[50.119, 49.123, 47.654, 49.228]])

In [46]:
array[2, [1, 3], [1]]

array([50.286, 48.496])

In [47]:
array[2][1::2, 1::3]

array([[50.286],
       [48.496]])

In [48]:
array[::, [0, 1, 2, 3, 4], [2]]

array([[50.991, 48.389, 50.085, 48.554, 47.654],
       [53.882, 49.476, 56.354, 51.94 , 50.502],
       [49.784, 50.107, 50.963, 52.637, 46.254]])

In [49]:
array[::, ::, 2::-3]

array([[[50.991],
        [48.389],
        [50.085],
        [48.554],
        [47.654]],

       [[53.882],
        [49.476],
        [56.354],
        [51.94 ],
        [50.502]],

       [[49.784],
        [50.107],
        [50.963],
        [52.637],
        [46.254]]])

In [50]:
mask = array <=46

In [51]:
array[mask]

array([41.867, 44.333, 45.056])

In [52]:
array[::, [3, 3], [0, 1]]

array([[47.791, 49.511],
       [48.867, 56.128],
       [52.195, 48.496]])

In [53]:
array[:2:, [0, 1, 2, 3, 4], 1::]

array([[[52.465, 50.991, 46.091],
        [51.339, 48.389, 51.743],
        [50.882, 50.085, 51.64 ],
        [49.511, 48.554, 51.797],
        [49.123, 47.654, 49.228]],

       [[49.173, 53.882, 53.02 ],
        [44.333, 49.476, 48.733],
        [50.652, 56.354, 46.664],
        [56.128, 51.94 , 51.989],
        [45.056, 50.502, 50.327]]])

In [54]:
array[1, [3, 4], -1::-2]

array([[51.989, 56.128],
       [50.327, 45.056]])

In [55]:
array[2, 1] = 99

In [56]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [57]:
array[2, 1] = array[2, 1] + 0.5

In [58]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.5  , 99.5  , 99.5  , 99.5  ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [59]:
array[1, 0:2, 2] = [53.872, 49.479]

In [60]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.872, 53.02 ],
        [41.867, 44.333, 49.479, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.5  , 99.5  , 99.5  , 99.5  ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])