In [1]:
import numpy as np

In [2]:
list_3d = [
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18],
        [19,20,21],
        [22,23,24]
    ]
]

array_3d = np.array(list_3d)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [3]:
array_3d.shape

(2, 4, 3)

In [4]:
list_3d[1]

[[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]

In [5]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [6]:
array_3d[1][2]

array([19, 20, 21])

In [7]:
array_3d[1][2][0]

19

In [8]:
array_3d[1][2][1]

20

In [9]:
array_3d[[0, 1]]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [10]:
array_3d[:, [0,1]]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
array_3d[-1, -2, -2]

20

In [12]:
mask = [True, True]
array_3d[mask]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [13]:
mask = [False, True]
array_3d[mask]

array([[[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [14]:
mask = array_3d % 2 == 0
mask

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]]])

In [15]:
array_3d[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [16]:
array_3d[:1]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
array_3d[:, 1:3]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [18]:
array_3d[:, 1:3, 0:-1]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]]])

In [19]:
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
array_3d[0, 1:4:2]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [21]:
array_3d[0, 1::2]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [22]:
array_3d[0, ::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
array_3d[0, ::-2]

array([[10, 11, 12],
       [ 4,  5,  6]])

In [24]:
array_3d[0, ::-1]

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [25]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [26]:
array_3d[1][2][0]

19

In [27]:
array_3d[1,2,0]

19

In [28]:
array_3d[1,2,0] = 50
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [50, 20, 21],
        [22, 23, 24]]])

In [29]:
array_3d[:, 1:3, 0:-1] = np.array([
    [
        [64,65],
        [67,68]
    ],
    [
        [76, 77],
        [79, 80]
    ]
])

In [30]:
array_3d

array([[[ 1,  2,  3],
        [64, 65,  6],
        [67, 68,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [76, 77, 18],
        [79, 80, 21],
        [22, 23, 24]]])

In [31]:
array_3d[0]

array([[ 1,  2,  3],
       [64, 65,  6],
       [67, 68,  9],
       [10, 11, 12]])

In [32]:
array_3d[0] = 99
array_3d

array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]],

       [[13, 14, 15],
        [76, 77, 18],
        [79, 80, 21],
        [22, 23, 24]]])