In [29]:
import numpy as np

In [30]:
np.__version__

'1.26.4'

In [31]:
list_a = [1, 2, 3, 4]

In [32]:
type(list_a)

list

In [33]:
print(id(list_a))

125407540131840


In [34]:
list_a.append(5)
print(list_a)
print(id(list_a))

[1, 2, 3, 4, 5]
125407540131840


In [35]:
array_a = np.array([1, 2, 3, 4])

In [36]:
type(array_a)

numpy.ndarray

In [37]:
print(id(array_a))

125408831817264


In [38]:
array_a = np.append(array_a, [5])
print(array_a)
print(id(array_a))

[1 2 3 4 5]
125408831817168


In [39]:
list_a = [1, 2.4, 'a', True, 5]
print(list_a)

[1, 2.4, 'a', True, 5]


In [40]:
type(list_a)

list

In [41]:
for i in array_a:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [42]:
array_a.dtype

dtype('int64')

In [43]:
list_a = [1, 2, 3, 4]
list_b = [5, 6, 7, 8]

list_c = list_a + list_b
print(list_c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [44]:
list_a[0], list_a[1], list_a[2], list_a[3]

(1, 2, 3, 4)

In [45]:
list_c = []
for i in range(4):
    list_c.append(list_a[i] + list_b[i])
print(list_c)

[6, 8, 10, 12]


In [46]:
array_a = np.array([list_a])
array_b = np.array([list_b])

array_c = array_a + array_b

In [47]:
print(array_c)

[[ 6  8 10 12]]


In [48]:
array_a - array_b

array([[-4, -4, -4, -4]])

In [49]:
array_a + array_b

array([[ 6,  8, 10, 12]])

In [50]:
array_a * array_b

array([[ 5, 12, 21, 32]])

In [51]:
array_a / array_b

array([[0.2       , 0.33333333, 0.42857143, 0.5       ]])

In [52]:
array_a % array_b

array([[1, 2, 3, 4]])

In [53]:
array_a ** array_b

array([[    1,    64,  2187, 65536]])

In [54]:
list_a = [1, 2, 3, 4]
list_a.append(5)
# list_a is now [1, 2, 3, 4, 5]

In [55]:
list_b = []
for i in list_a:
    list_b.append(i + 5)
    print(list_b)

[6]
[6, 7]
[6, 7, 8]
[6, 7, 8, 9]
[6, 7, 8, 9, 10]


In [56]:
array_a = np.array([1, 2, 3, 4])
array_a + 5

array([6, 7, 8, 9])

In [57]:
array_b = np.array([[5], [10]])

In [58]:
array_b

array([[ 5],
       [10]])

In [59]:
array_b.shape

(2, 1)

In [60]:
array_a

array([1, 2, 3, 4])

In [61]:
array_a + array_b

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [62]:
array_b = np.array([[5, 6], [10, 11]])

In [63]:
array_b.shape

(2, 2)

In [64]:
array_a + array_b

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 