In [923]:
import numpy as np

In [924]:
np.zeros(shape=3)

array([0., 0., 0.])

In [925]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [926]:
np.zeros(shape=(3, 3)).dtype

dtype('float64')

In [927]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [928]:
np.full(shape=(3, 3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [929]:
array = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [930]:
array.shape

(2, 3)

In [931]:
np.zeros_like(a = array)

array([[0, 0, 0],
       [0, 0, 0]])

In [932]:
np.ones_like(a = array)

array([[1, 1, 1],
       [1, 1, 1]])

In [933]:
np.full_like(a = array, fill_value = 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [934]:
np.empty(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [935]:
np.eye(N = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [936]:
np.identity(n = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [937]:
np.arange(start=0, stop = 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [938]:
np.arange(start = 3, stop = 10)

array([3, 4, 5, 6, 7, 8, 9])

In [939]:
np.arange(start = 3, stop = 10, step = 3)

array([3, 6, 9])

In [940]:
np.arange(start = 3, stop = 10, step = -2)

array([], dtype=int64)

In [941]:
np.arange(start = 3, stop = 10, step = 0.25)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
       5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25,
       8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [942]:
np.linspace(start = 1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [943]:
np.linspace(start = 1, stop = 10, num = 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [944]:
np.logspace(start = 1, stop = 4, num = 4)

array([   10.,   100.,  1000., 10000.])

In [945]:
np.geomspace(start = 10, stop = 10000, num = 4)

array([   10.,   100.,  1000., 10000.])

In [971]:
np.geomspace(start = 3, stop = 48000, num = 6).astype(int)

array([    3,    20,   144,   999,  6924, 48000])